services:

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: full-auth
    ports:
      - 5432:5432
    volumes:
     - ./data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - backend


volumes:
  postgres_data:
  redis_data:

networks:
  backend: